POST http://localhost:9000/client/token HTTP/1.1
content-type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVlNmJiYmVmYzk2YmJkMDViMDU4MTEwZiIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXh0IiwibGFzdE5hbWUiOiJ0ZXh0dCIsImltYWdlIjoibnVsbCIsImNyZWF0aW9uVHlwZSI6ImdtYWlsIiwiY3JlYXRlZE9uIjoiMjAyMC0wMy0xM1QxNjo1OToyNy4xOTFaIiwidXBkYXRlZE9uIjoiMjAyMC0wMy0xNFQxNjoyMzo1Ny44MjBaIiwiX192IjowfSwiaWF0IjoxNTg0MjAzMDM3fQ.7TkhBQS0mcO32BK0GhkZ4u05Tbd2cKiVgnhgdGwYTSY"
}

###

POST http://localhost:9000/client/signin HTTP/1.1
content-type: application/json

{
    "id": 1111,
    "email": "test@gmail.com",
    "firstName": "text",
    "lastName": "textt",
    "image": "null",
    "loginType": "gmail"
}


###

POST http://localhost:9000/client/signup HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVlNmJiYmVmYzk2YmJkMDViMDU4MTEwZiIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXh0IiwibGFzdE5hbWUiOiJ0ZXh0dCIsImltYWdlIjoibnVsbCIsImNyZWF0aW9uVHlwZSI6ImdtYWlsIiwiY3JlYXRlZE9uIjoiMjAyMC0wMy0xM1QxNjo1OToyNy4xOTFaIiwidXBkYXRlZE9uIjoiMjAyMC0wMy0xNFQxNjoxODo0NS44NzdaIiwiX192IjowfSwiaWF0IjoxNTg0MjAyNzI1fQ.clQcV1YZPu4EjRBO1SrJqZIqUB85qtZP_3t4a9iOX58